name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform Action'
        required: true
        default: 'plan'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.1.0"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.0
        terraform_wrapper: false 

    - name: Terraform Init
      run: terraform init

    - if: github.event.inputs.terraform_action == 'plan'
      name: Terraform Plan
      run: terraform plan -input=false

    - if: github.event.inputs.terraform_action == 'apply'
      name: Terraform Apply
      run: terraform apply -auto-approve -input=false -no-color 

    - if: github.event.inputs.terraform_action == 'destroy'
      name: Terraform Destroy
      run: terraform destroy -auto-approve
